## 3.2 Data Preparation

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'matplotlib.backends.registry'

In [ ]:
data = "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv"

In [ ]:
!wget -nc $data -O data_week3.csv #-O with file name is instructing python to save it under that name

'wget' is not recognized as an internal or external command,
operable program or batch file.

In [ ]:
df = pd.read_csv("data_week3.csv")

In [ ]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Transposing the columns to have a look at all of them

In [ ]:
df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [ ]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [ ]:
df.head().T

,0,1,2,3,4
customerid,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
seniorcitizen,0,0,0,0,0
partner,Yes,No,No,No,No
dependents,No,No,No,No,No
tenure,1,34,2,45,2
phoneservice,No,Yes,Yes,No,Yes
multiplelines,No phone service,No,No,No phone service,No
internetservice,DSL,DSL,DSL,DSL,Fiber optic
onlinesecurity,No,Yes,Yes,Yes,No
onlinebackup,Yes,No,Yes,No,No
deviceprotection,No,Yes,No,Yes,No
techsupport,No,No,No,Yes,No
streamingtv,No,No,No,No,No
streamingmovies,No,No,No,No,No
contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
paperlessbilling,Yes,No,Yes,No,Yes
paymentmethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,No,No,Yes,No,Yes

In [ ]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

In [ ]:
df.totalcharges

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: totalcharges, Length: 7043, dtype: str

Convert it into an integer

In [ ]:
import traceback

try:
    pd.to_numeric(df.totalcharges)

except Exception as e:
    print(e)
    traceback.print_exc()

Unable to parse string " " at position 488

Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 2478, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string " "

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Temp\ipykernel_4188\1359771946.py", line 4, in <module>
    pd.to_numeric(df.totalcharges)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "e:\Data Science\gachau_learning\venv\Lib\site-packages\pandas\core\tools\numeric.py", line 235, in to_numeric
    values, new_mask = lib.maybe_convert_numeric(  # type: ignore[call-overload]
                       ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        values,
        ^^^^^^^
    ...<6 lines>...
        ),
        ^^
    )
    ^
  File "pandas/_libs/lib.pyx", line 2521, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string " " at position 488

ValueError: Unable to parse string "_"
The error above was because I replaced all spaces with underscores including spaces in the column totalcharges

In [ ]:
tc = pd.to_numeric(df.totalcharges, errors='coerce')
df[tc.isnull()]

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [ ]:
df[tc.isnull()][['customerid', 'totalcharges']]

      customerid totalcharges
488   4472-LVYGI
753   3115-CZMZD
936   5709-LVOEQ
1082  4367-NUYAO
1340  1371-DWPAZ
3331  7644-OMVMY
3826  3213-VVOLG
4380  2520-SGTTA
5218  2923-ARZLG
6670  4075-WKNIU
6754  2775-SEFEE

In [ ]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors = 'coerce')
df.totalcharges = df.totalcharges.fillna(0)

In [ ]:
df[tc.isnull()][['customerid', 'totalcharges']]

      customerid  totalcharges
488   4472-LVYGI           0.0
753   3115-CZMZD           0.0
936   5709-LVOEQ           0.0
1082  4367-NUYAO           0.0
1340  1371-DWPAZ           0.0
3331  7644-OMVMY           0.0
3826  3213-VVOLG           0.0
4380  2520-SGTTA           0.0
5218  2923-ARZLG           0.0
6670  4075-WKNIU           0.0
6754  2775-SEFEE           0.0

### Checking the churn variable

Need to be turned into numbers
1 = Yes
0 = No

In [ ]:
df.churn.head()

0     No
1     No
2    Yes
3     No
4    Yes
Name: churn, dtype: str

In [ ]:
(df.churn == 'yes').astype(int).head()

0    0
1    0
2    0
3    0
4    0
Name: churn, dtype: int64

In [ ]:
df['churn'] = (df['churn'] == 'yes').astype(int)

## 3.3 Setting up the validation framework

- Perform the train/val/test split with Scikit-Learn

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
len(df_full_train), len(df_test)

(5634, 1409)

In [ ]:
df_train, df_val = train_test_split(df_full_train, test_size=0.2, random_state=1)
len(df_train), len(df_val), len(df_test)

(4507, 1127, 1409)

df_val has an issue because it is 20% of df_full_train and not 20% of the entire df. To fix this, we need to make df_val 20%/80% * 100 which is 25%

In [ ]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [ ]:
df_train

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
3897,8015-IHCGW,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.50,8425.15,0
1980,1960-UYCNN,Male,0,No,No,10,Yes,Yes,Fiber optic,No,...,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,95.25,1021.55,0
6302,9250-WYPLL,Female,0,No,No,5,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,No,Electronic check,75.55,413.65,0
727,6786-OBWQR,Female,0,Yes,Yes,5,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.85,356.10,0
5104,1328-EUZHC,Female,0,Yes,No,18,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.10,370.50,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3774,1309-XGFSN,Male,1,Yes,Yes,52,Yes,Yes,DSL,No,...,Yes,No,Yes,Yes,One year,Yes,Electronic check,80.85,4079.55,0
6108,4819-HJPIW,Male,0,No,No,18,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,No,Mailed check,25.15,476.80,0
1530,3703-VAVCL,Male,0,Yes,Yes,2,Yes,No,Fiber optic,No,...,Yes,Yes,No,Yes,Month-to-month,No,Credit card (automatic),90.00,190.05,0
3701,3812-LRZIR,Female,0,Yes,Yes,27,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Electronic check,24.50,761.95,0
4368,1704-NRWYE,Female,1,No,No,9,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.85,751.65,0

Reset index

In [ ]:
df_train.reset_index(drop=True)
df_val.reset_index(drop=True)
df_test.reset_index(drop=True)

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,8879-ZKJOF,Female,0,No,No,41,Yes,No,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),79.85,3320.75,0
1,0201-MIBOL,Female,1,No,No,66,Yes,Yes,Fiber optic,Yes,...,No,No,Yes,Yes,Two year,Yes,Bank transfer (automatic),102.40,6471.85,0
2,1600-DILPE,Female,0,No,No,12,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),45.00,524.35,0
3,8601-QACRS,Female,0,No,No,5,Yes,Yes,DSL,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,50.60,249.95,0
4,7919-ZODZZ,Female,0,Yes,Yes,10,Yes,No,DSL,No,...,Yes,No,No,Yes,One year,Yes,Mailed check,65.90,660.05,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1404,5130-IEKQT,Male,1,No,No,25,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,No,Mailed check,105.95,2655.25,0
1405,4452-ROHMO,Female,0,No,No,15,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.60,331.60,0
1406,6164-HAQTX,Male,0,No,No,71,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Bank transfer (automatic),53.95,3888.65,0
1407,3982-DQLUS,Male,1,Yes,Yes,65,Yes,Yes,Fiber optic,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,85.75,5688.45,0
1408,9874-QLCLH,Female,0,Yes,Yes,17,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,104.20,1743.50,0

In [ ]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

We delete this variable to avoid using it accidentally later

Please note the churn variable is not deleted in the df_train_full

In [ ]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

## 3.4 EDA

- Check missing values
- Look at the target variable (churn)
- Look at the numerical and categorical variables

In [ ]:
df_full_train = df_full_train.reset_index(drop=True)

In [ ]:
df_full_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [ ]:
df_full_train['churn'].value_counts(),df_full_train['churn'].value_counts(normalize=True)

(churn
 0    5634
 Name: count, dtype: int64,
 churn
 0    1.0
 Name: proportion, dtype: float64)

The churn rate is 27% which can also be gotten by getting the mean of churn

In [ ]:
global_churn = df_full_train['churn'].mean()
round(global_churn, 2)

np.float64(0.0)

In [ ]:
df_full_train.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='str')

In [ ]:
numerical = [
    'tenure',
    'monthlycharges',
    'totalcharges'
]

In [ ]:
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
        'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod']

In [ ]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

## 3.5 Feature Importance: Churn rate and risk ratio
Feature importance analysis(part EDA) - identifying which features affect our target variables

- Churn rate
- Risk Ratio
- Mutual information - later

what is the churn rate per variable

In [ ]:
churn_female = df_full_train[df_full_train['gender']== 'female'].churn.mean()
churn_female

nan

In [ ]:
churn_male = df_full_train[df_full_train['gender']== 'male'].churn.mean()
churn_male

nan

churn is not dependent on gender

In [ ]:
df_full_train['partner'].value_counts()

partner
No     2932
Yes    2702
Name: count, dtype: int64

In [ ]:
churn_partner = df_full_train[df_full_train['partner']== 'yes'].churn.mean()
churn_partner

nan

In [ ]:
global_churn - churn_partner

np.float64(nan)

The difference is positive 6% therefore this group is less likely to churn

In [ ]:
churn_no_partner = df_full_train[df_full_train['partner']== 'no'].churn.mean()
churn_no_partner

nan

In [ ]:
global_churn - churn_no_partner

np.float64(nan)

The difference is negative 6% therefore this group is most likely to churn

partner variable seems significant.

Therefore we should consider it when creating our model

### Risk Ratio

Numbers higher than 1 seem more likely to churn

In [ ]:
churn_no_partner/global_churn #the churn rate of people without partners is 22% higher than the global churn rate.

np.float64(nan)

In [ ]:
churn_partner/global_churn #the churn rate of people with partners is 24.1% lower than the global churn rate.

np.float64(nan)

In [ ]:
for c in categorical:
    for category in df_full_train[c].unique():
        churn_rate = df_full_train[df_full_train[c] == category].churn.mean()
        global_churn = df_full_train['churn'].mean()
        difference = churn_rate / global_churn
        if difference > 1:
            print(f"{c}: {category} - Difference: {difference}")

C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn
C:\Users\PC\AppData\Local\Temp\ipykernel_4188\2798953097.py:5: RuntimeWarning: invalid value encountered in scalar divide
  difference = churn_rate / global_churn

SELECT
    
        gender,
        AVG(churn),    
        AVG(churn) - global_churn AS diff,    
        AVG(churn) / global_churn AS risk

FROM
            data

GROUP BY
            gender;

Translate this SQL query to pandas

In [ ]:
df_full_train.groupby('gender').churn.mean()

gender
Female    0.0
Male      0.0
Name: churn, dtype: float64

To get a dataframe ,so that we can add the diff and risk columns, instead of a series, we use the aggregate function

In [ ]:
df_group = df_full_train.groupby('gender').churn.agg(['mean', 'count'])

Add columns

In [ ]:
df_group['diff'] = df_group['mean'] - global_churn
df_group['risk'] = df_group['mean'] / global_churn
df_group

        mean  count  diff  risk
gender
Female   0.0   2796   0.0   NaN
Male     0.0   2838   0.0   NaN

In [ ]:
from IPython.display import display

In [ ]:
for c in categorical:
    print(c)
    df_group = df_full_train.groupby(c).churn.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - global_churn
    df_group['risk'] = df_group['mean'] / global_churn
    display(df_group)
    print()
    print()

gender

        mean  count  diff  risk
gender
Female   0.0   2796   0.0   NaN
Male     0.0   2838   0.0   NaN

seniorcitizen

               mean  count  diff  risk
seniorcitizen
0               0.0   4722   0.0   NaN
1               0.0    912   0.0   NaN

partner

         mean  count  diff  risk
partner
No        0.0   2932   0.0   NaN
Yes       0.0   2702   0.0   NaN

dependents

            mean  count  diff  risk
dependents
No           0.0   3968   0.0   NaN
Yes          0.0   1666   0.0   NaN

phoneservice

              mean  count  diff  risk
phoneservice
No             0.0    547   0.0   NaN
Yes            0.0   5087   0.0   NaN

multiplelines

                  mean  count  diff  risk
multiplelines
No                 0.0   2700   0.0   NaN
No phone service   0.0    547   0.0   NaN
Yes                0.0   2387   0.0   NaN

internetservice

                 mean  count  diff  risk
internetservice
DSL               0.0   1934   0.0   NaN
Fiber optic       0.0   2479   0.0   NaN
No                0.0   1221   0.0   NaN

onlinesecurity

                     mean  count  diff  risk
onlinesecurity
No                    0.0   2801   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   1612   0.0   NaN

onlinebackup

                     mean  count  diff  risk
onlinebackup
No                    0.0   2498   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   1915   0.0   NaN

deviceprotection

                     mean  count  diff  risk
deviceprotection
No                    0.0   2473   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   1940   0.0   NaN

techsupport

                     mean  count  diff  risk
techsupport
No                    0.0   2781   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   1632   0.0   NaN

streamingtv

                     mean  count  diff  risk
streamingtv
No                    0.0   2246   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   2167   0.0   NaN

streamingmovies

                     mean  count  diff  risk
streamingmovies
No                    0.0   2213   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   2200   0.0   NaN

contract

                mean  count  diff  risk
contract
Month-to-month   0.0   3104   0.0   NaN
One year         0.0   1186   0.0   NaN
Two year         0.0   1344   0.0   NaN

paperlessbilling

                  mean  count  diff  risk
paperlessbilling
No                 0.0   2313   0.0   NaN
Yes                0.0   3321   0.0   NaN

paymentmethod

                           mean  count  diff  risk
paymentmethod
Bank transfer (automatic)   0.0   1219   0.0   NaN
Credit card (automatic)     0.0   1217   0.0   NaN
Electronic check            0.0   1893   0.0   NaN
Mailed check                0.0   1305   0.0   NaN

## 3.6 Feature Importance : Mutual Information

Mutual information - concept from information theory, it tells us how much we can learn about one variable if we know the value of another

In [ ]:
from sklearn.metrics import mutual_info_score

In [ ]:
mutual_info_score(df_full_train['churn'], df_full_train['contract']) #Order doesn't matter for mutual information. It is symmetric, meaning that the mutual information between two variables is the same regardless of which variable is considered first.

0.0

In [ ]:
mutual_info_score(df_full_train['gender'], df_full_train['churn'])

0.0

In [ ]:
for c in categorical:
    mi = mutual_info_score(df_full_train['churn'], df_full_train[c])
    print(f"{c}: {mi:.4f}")

gender: 0.0000
seniorcitizen: 0.0000
partner: 0.0000
dependents: 0.0000
phoneservice: 0.0000
multiplelines: 0.0000
internetservice: 0.0000
onlinesecurity: 0.0000
onlinebackup: 0.0000
deviceprotection: 0.0000
techsupport: 0.0000
streamingtv: 0.0000
streamingmovies: 0.0000
contract: 0.0000
paperlessbilling: 0.0000
paymentmethod: 0.0000

In [ ]:
def mutual_info_churn_score(series):   
    return mutual_info_score(series, df_full_train['churn'])

In [ ]:
df_full_train[categorical].apply(mutual_info_churn_score).sort_values(ascending=False)

gender              0.0
seniorcitizen       0.0
partner             0.0
dependents          0.0
phoneservice        0.0
multiplelines       0.0
internetservice     0.0
onlinesecurity      0.0
onlinebackup        0.0
deviceprotection    0.0
techsupport         0.0
streamingtv         0.0
streamingmovies     0.0
contract            0.0
paperlessbilling    0.0
paymentmethod       0.0
dtype: float64

## 3.7 Feature Importance: Correlation

How about numerical columns?

- Correlation coefficient - a way of measuring the degree of dependency between two variables

In [ ]:
df_full_train[numerical].corrwith(df_full_train['churn'])

e:\Data Science\gachau_learning\venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3036: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
e:\Data Science\gachau_learning\venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3037: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

tenure           NaN
monthlycharges   NaN
totalcharges     NaN
dtype: float64

In [ ]:
df_full_train[numerical].corrwith(df_full_train['churn']).abs() #.abosolute figures showing order of importance of numerical features. The higher the absolute value, the more important the feature is in predicting churn.

e:\Data Science\gachau_learning\venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3036: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
e:\Data Science\gachau_learning\venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3037: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

tenure           NaN
monthlycharges   NaN
totalcharges     NaN
dtype: float64

In [ ]:
df_full_train[numerical].corrwith(df_full_train['churn'])

e:\Data Science\gachau_learning\venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3036: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
e:\Data Science\gachau_learning\venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3037: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

tenure           NaN
monthlycharges   NaN
totalcharges     NaN
dtype: float64

- When tenure and total charges(the longer they stay with the company) increases, the less likely to churn

- The higher the monthly charges are, the more they are likely to leave

In [ ]:
df_full_train[df_full_train.tenure <= 2].churn.mean()

np.float64(0.0)

The churn rate of people who have been with the company for less than 2 months is really high

In [ ]:
df_full_train[(df_full_train.tenure > 2) & (df_full_train.tenure <= 12)].churn.mean()

np.float64(0.0)

In [ ]:
df_full_train[df_full_train.tenure > 12].churn.mean()

np.float64(0.0)

- Between 2 months and 12 months the churn rate is 0.39
- The churn rate beyond 12 months is 0.17

## 3.8 One-hot encoding

- Using Scikit-Learn to encode categorical features

In [ ]:
from sklearn.feature_extraction import DictVectorizer

In [ ]:
df_full_train[['gender', 'contract']].iloc[:10].to_dict

<bound method DataFrame.to_dict of    gender        contract
0    Male        Two year
1  Female        One year
2    Male        Two year
3    Male        One year
4    Male        One year
5  Female  Month-to-month
6    Male        Two year
7    Male  Month-to-month
8    Male  Month-to-month
9  Female  Month-to-month>

In [ ]:
dicts = df_full_train[['gender', 'contract']].iloc[:10].to_dict(orient='records')
dicts

[{'gender': 'Male', 'contract': 'Two year'},
 {'gender': 'Female', 'contract': 'One year'},
 {'gender': 'Male', 'contract': 'Two year'},
 {'gender': 'Male', 'contract': 'One year'},
 {'gender': 'Male', 'contract': 'One year'},
 {'gender': 'Female', 'contract': 'Month-to-month'},
 {'gender': 'Male', 'contract': 'Two year'},
 {'gender': 'Male', 'contract': 'Month-to-month'},
 {'gender': 'Male', 'contract': 'Month-to-month'},
 {'gender': 'Female', 'contract': 'Month-to-month'}]

In [ ]:
dv = DictVectorizer() #takes a dictionary and converts it into a feature matrix. It is used to convert categorical features into numerical features.

Then train it

In [ ]:
dv.fit(dicts)

DictVectorizer()

In [ ]:
dv.transform(dicts)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 20 stored elements and shape (10, 5)>

It produces a Sparse Matrix which is a special way of encoding data when there are many zeros

In [ ]:
dv = DictVectorizer(sparse=False) #Sparse matrix is a matrix that is mostly filled with zeros. It is used to save memory when working with large datasets.

In [ ]:
dv.fit(dicts)
dv.transform(dicts)

array([[0., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

Let us take the whole dataset ie df_train and not df_train_full

In [ ]:
train_dicts = df_train[categorical + numerical].to_dict(orient='records')
train_dicts[0]

{'gender': 'Female',
 'seniorcitizen': 0,
 'partner': 'Yes',
 'dependents': 'Yes',
 'phoneservice': 'Yes',
 'multiplelines': 'Yes',
 'internetservice': 'Fiber optic',
 'onlinesecurity': 'Yes',
 'onlinebackup': 'Yes',
 'deviceprotection': 'Yes',
 'techsupport': 'Yes',
 'streamingtv': 'Yes',
 'streamingmovies': 'Yes',
 'contract': 'Two year',
 'paperlessbilling': 'Yes',
 'paymentmethod': 'Electronic check',
 'tenure': 72,
 'monthlycharges': 115.5,
 'totalcharges': 8425.15}

In [ ]:
dv = DictVectorizer(sparse=False)
dv.fit(train_dicts)

DictVectorizer(sparse=False)

In [ ]:
dv.get_feature_names_out()

array(['contract=Month-to-month', 'contract=One year',
       'contract=Two year', 'dependents=No', 'dependents=Yes',
       'deviceprotection=No', 'deviceprotection=No internet service',
       'deviceprotection=Yes', 'gender=Female', 'gender=Male',
       'internetservice=DSL', 'internetservice=Fiber optic',
       'internetservice=No', 'monthlycharges', 'multiplelines=No',
       'multiplelines=No phone service', 'multiplelines=Yes',
       'onlinebackup=No', 'onlinebackup=No internet service',
       'onlinebackup=Yes', 'onlinesecurity=No',
       'onlinesecurity=No internet service', 'onlinesecurity=Yes',
       'paperlessbilling=No', 'paperlessbilling=Yes', 'partner=No',
       'partner=Yes', 'paymentmethod=Bank transfer (automatic)',
       'paymentmethod=Credit card (automatic)',
       'paymentmethod=Electronic check', 'paymentmethod=Mailed check',
       'phoneservice=No', 'phoneservice=Yes', 'seniorcitizen',
       'streamingmovies=No', 'streamingmovies=No internet service',
       'streamingmovies=Yes', 'streamingtv=No',
       'streamingtv=No internet service', 'streamingtv=Yes',
       'techsupport=No', 'techsupport=No internet service',
       'techsupport=Yes', 'tenure', 'totalcharges'], dtype=object)

In [ ]:
X_train = dv.transform(train_dicts)
X_train.shape

(4225, 45)

In [ ]:
X_train = dv.fit_transform(train_dicts) #Same output by combining fit and transform into one step. It is used to save time when working with large datasets.    
X_train.shape

(4225, 45)

We do not fit the validation data because we want to use the same features as the training data. We only transform the validation data using the same DictVectorizer that was fitted on the training data.

In [ ]:
val_dicts = df_val[categorical + numerical].to_dict(orient='records')

In [ ]:
X_val = dv.transform(val_dicts)

## 3.9 Logistic Regression

- Binary Classification
- Linear Vs Logistic Regression

We use sigmoid to transform a score into a probability

In [ ]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

Ploting the sigmoid

Get a 100 numbers between -7 to 7

In [ ]:
z = np.linspace(-7, 7, 100)
z

array([-7.        , -6.85858586, -6.71717172, -6.57575758, -6.43434343,
       -6.29292929, -6.15151515, -6.01010101, -5.86868687, -5.72727273,
       -5.58585859, -5.44444444, -5.3030303 , -5.16161616, -5.02020202,
       -4.87878788, -4.73737374, -4.5959596 , -4.45454545, -4.31313131,
       -4.17171717, -4.03030303, -3.88888889, -3.74747475, -3.60606061,
       -3.46464646, -3.32323232, -3.18181818, -3.04040404, -2.8989899 ,
       -2.75757576, -2.61616162, -2.47474747, -2.33333333, -2.19191919,
       -2.05050505, -1.90909091, -1.76767677, -1.62626263, -1.48484848,
       -1.34343434, -1.2020202 , -1.06060606, -0.91919192, -0.77777778,
       -0.63636364, -0.49494949, -0.35353535, -0.21212121, -0.07070707,
        0.07070707,  0.21212121,  0.35353535,  0.49494949,  0.63636364,
        0.77777778,  0.91919192,  1.06060606,  1.2020202 ,  1.34343434,
        1.48484848,  1.62626263,  1.76767677,  1.90909091,  2.05050505,
        2.19191919,  2.33333333,  2.47474747,  2.61616162,  2.75757576,
        2.8989899 ,  3.04040404,  3.18181818,  3.32323232,  3.46464646,
        3.60606061,  3.74747475,  3.88888889,  4.03030303,  4.17171717,
        4.31313131,  4.45454545,  4.5959596 ,  4.73737374,  4.87878788,
        5.02020202,  5.16161616,  5.3030303 ,  5.44444444,  5.58585859,
        5.72727273,  5.86868687,  6.01010101,  6.15151515,  6.29292929,
        6.43434343,  6.57575758,  6.71717172,  6.85858586,  7.        ])

The sigmoid function is used to convert the output of a linear regression model into a probability. It is used in logistic regression to predict the probability of a binary outcome (zeros and ones).

In [ ]:
sigmoid(z) #gets numbers between 0 and 1.

array([9.11051194e-04, 1.04929612e-03, 1.20849325e-03, 1.39180981e-03,
       1.60288907e-03, 1.84592104e-03, 2.12572334e-03, 2.44783371e-03,
       2.81861552e-03, 3.24537821e-03, 3.73651433e-03, 4.30165529e-03,
       4.95184793e-03, 5.69975424e-03, 6.55987647e-03, 7.54881014e-03,
       8.68552699e-03, 9.99168994e-03, 1.14920016e-02, 1.32145869e-02,
       1.51914098e-02, 1.74587216e-02, 2.00575365e-02, 2.30341287e-02,
       2.64405363e-02, 3.03350596e-02, 3.47827268e-02, 3.98556989e-02,
       4.56335711e-02, 5.22035186e-02, 5.96602230e-02, 6.81055013e-02,
       7.76475461e-02, 8.83996772e-02, 1.00478499e-01, 1.14001359e-01,
       1.29083018e-01, 1.45831484e-01, 1.64342987e-01, 1.84696201e-01,
       2.06945849e-01, 2.31116029e-01, 2.57193653e-01, 2.85122575e-01,
       3.14799023e-01, 3.46069006e-01, 3.78728288e-01, 4.12525370e-01,
       4.47167650e-01, 4.82330593e-01, 5.17669407e-01, 5.52832350e-01,
       5.87474630e-01, 6.21271712e-01, 6.53930994e-01, 6.85200977e-01,
       7.14877425e-01, 7.42806347e-01, 7.68883971e-01, 7.93054151e-01,
       8.15303799e-01, 8.35657013e-01, 8.54168516e-01, 8.70916982e-01,
       8.85998641e-01, 8.99521501e-01, 9.11600323e-01, 9.22352454e-01,
       9.31894499e-01, 9.40339777e-01, 9.47796481e-01, 9.54366429e-01,
       9.60144301e-01, 9.65217273e-01, 9.69664940e-01, 9.73559464e-01,
       9.76965871e-01, 9.79942463e-01, 9.82541278e-01, 9.84808590e-01,
       9.86785413e-01, 9.88507998e-01, 9.90008310e-01, 9.91314473e-01,
       9.92451190e-01, 9.93440124e-01, 9.94300246e-01, 9.95048152e-01,
       9.95698345e-01, 9.96263486e-01, 9.96754622e-01, 9.97181384e-01,
       9.97552166e-01, 9.97874277e-01, 9.98154079e-01, 9.98397111e-01,
       9.98608190e-01, 9.98791507e-01, 9.98950704e-01, 9.99088949e-01])

In [ ]:
plt.plot(z, sigmoid(z))

NameError: name 'plt' is not defined

In [ ]:
def linear_regression(xi, w0, w):
    result = w0
    
    for j in range(len(w)):
        result = result + xi[j] * w[j]
    
    return result

In [ ]:
def logistic_regression(xi, w0, w):
    score = w0
    
    for j in range(len(w)):
        score = score + w[j] * xi[j]
        
    result = sigmoid(score)
    return result

## 3.10 Training logistic regression with Scikit-learn

- Train a model with Scikit-Learn
- Apply it to the validation dataset
- Calculate the accuracy

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: np.int64(0)

w0

In [ ]:
model.intercept_[0]

np.float64(-0.10910575411731115)

These are the weights

In [ ]:
model.coef_

array([[ 4.75717837e-01, -1.74974117e-01, -4.08489634e-01,
        -2.99885245e-02, -7.77573894e-02,  6.26589495e-02,
        -8.90715400e-02, -8.13333235e-02, -3.43043508e-02,
        -7.34415631e-02, -3.35503209e-01,  3.16828835e-01,
        -8.90715400e-02,  3.68850280e-03, -2.58257758e-01,
         1.41848117e-01,  8.66372707e-03,  6.25260874e-02,
        -8.90715400e-02, -8.12004613e-02,  2.65657105e-01,
        -8.90715400e-02, -2.84331479e-01, -2.31072067e-01,
         1.23326153e-01, -1.66360757e-01,  5.86148436e-02,
        -8.70789120e-02, -3.19911720e-02,  7.00844586e-02,
        -5.87602885e-02,  1.41848117e-01, -2.49594031e-01,
         2.15655184e-01, -1.20527699e-01, -8.90715400e-02,
         1.01853325e-01, -7.09790548e-02, -8.90715400e-02,
         5.23046809e-02,  2.13260458e-01, -8.90715400e-02,
        -2.31934832e-01, -7.04966672e-02,  3.83087375e-04]])

In [ ]:
model.predict(X_train)

array([0, 1, 1, ..., 1, 0, 1], shape=(4225,))

Hard Prediction because we already know the labels Note it only predicts 1s and 0s

In [ ]:
model.predict_proba(X_train)

array([[0.90452492, 0.09547508],
       [0.32058285, 0.67941715],
       [0.36630247, 0.63369753],
       ...,
       [0.46766799, 0.53233201],
       [0.95761329, 0.04238671],
       [0.3012034 , 0.6987966 ]], shape=(4225, 2))

These are soft predictions because they are not 1s or 0s

2 dimension matrix with two columns
- First column is probability of it being negative
- Second column is probability of it being positive - the probability of churning

We take the second column

In [ ]:
model.predict_proba(X_train)[:,1]

array([0.09547508, 0.67941715, 0.63369753, ..., 0.53233201, 0.04238671,
       0.6987966 ], shape=(4225,))

Let's use the validation data set

In [ ]:
y_pred = model.predict_proba(X_val)[:,1]
y_pred

array([0.00896799, 0.20454216, 0.21215178, ..., 0.1363222 , 0.79995367,
       0.83758207], shape=(1409,))

In [ ]:
churn_decision = (y_pred >= 0.5)
churn_decision

array([False, False, False, ..., False,  True,  True], shape=(1409,))

Who are the people we should send promotional emails/messages? Who do we think will churn?

In [ ]:
df_val[churn_decision].customerid

2504    8433-wxgna
4597    3440-jpscl
2343    2637-fkfsy
5591    7228-omtpn
4482    6711-fldfb
           ...
2611    5976-jcjrh
4211    2034-cgrhz
3999    5276-kqwhg
6240    6521-yytyi
5282    3049-solay
Name: customerid, Length: 312, dtype: object

In [ ]:
churn_decision.astype(int)

array([0, 0, 0, ..., 0, 1, 1], shape=(1409,))

In [ ]:
y_val

array([0, 0, 0, ..., 0, 1, 1], shape=(1409,))

How many match?

In [ ]:
y_val == churn_decision

array([ True,  True,  True, ...,  True,  True,  True], shape=(1409,))

In [ ]:
(y_val == churn_decision).mean()

np.float64(0.8026969481902059)

80% of our predictions match

What does it look like in a dataframe

In [ ]:
df_pred = pd.DataFrame()
df_pred['churn_probability'] = y_pred
df_pred['prediction'] = churn_decision.astype(int)
df_pred['actual'] = y_val

In [ ]:
df_pred

      churn_probability  prediction  actual
0              0.008968           0       0
1              0.204542           0       0
2              0.212152           0       0
3              0.543024           1       1
4              0.213658           0       0
...                 ...         ...     ...
1404           0.313711           0       0
1405           0.039280           0       1
1406           0.136322           0       0
1407           0.799954           1       1
1408           0.837582           1       1

[1409 rows x 3 columns]

In [ ]:
df_pred['correct'] = df_pred['prediction'] == df_pred['actual']

In [ ]:
df_pred

      churn_probability  prediction  actual  correct
0              0.008968           0       0     True
1              0.204542           0       0     True
2              0.212152           0       0     True
3              0.543024           1       1     True
4              0.213658           0       0     True
...                 ...         ...     ...      ...
1404           0.313711           0       0     True
1405           0.039280           0       1    False
1406           0.136322           0       0     True
1407           0.799954           1       1     True
1408           0.837582           1       1     True

[1409 rows x 4 columns]

## 3.11 Model Interpretation

- Look at the coefficients
- Train a smaller model with fewer features

In [ ]:
dv.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'dependents=no', 'dependents=yes',
       'deviceprotection=no', 'deviceprotection=no_internet_service',
       'deviceprotection=yes', 'gender=female', 'gender=male',
       'internetservice=dsl', 'internetservice=fiber_optic',
       'internetservice=no', 'monthlycharges', 'multiplelines=no',
       'multiplelines=no_phone_service', 'multiplelines=yes',
       'onlinebackup=no', 'onlinebackup=no_internet_service',
       'onlinebackup=yes', 'onlinesecurity=no',
       'onlinesecurity=no_internet_service', 'onlinesecurity=yes',
       'paperlessbilling=no', 'paperlessbilling=yes', 'partner=no',
       'partner=yes', 'paymentmethod=bank_transfer_(automatic)',
       'paymentmethod=credit_card_(automatic)',
       'paymentmethod=electronic_check', 'paymentmethod=mailed_check',
       'phoneservice=no', 'phoneservice=yes', 'seniorcitizen',
       'streamingmovies=no', 'streamingmovies=no_internet_service',
       'streamingmovies=yes', 'streamingtv=no',
       'streamingtv=no_internet_service', 'streamingtv=yes',
       'techsupport=no', 'techsupport=no_internet_service',
       'techsupport=yes', 'tenure', 'totalcharges'], dtype=object)

In [ ]:
model.coef_[0].round(3)

array([ 0.476, -0.175, -0.408, -0.03 , -0.078,  0.063, -0.089, -0.081,
       -0.034, -0.073, -0.336,  0.317, -0.089,  0.004, -0.258,  0.142,
        0.009,  0.063, -0.089, -0.081,  0.266, -0.089, -0.284, -0.231,
        0.123, -0.166,  0.059, -0.087, -0.032,  0.07 , -0.059,  0.142,
       -0.25 ,  0.216, -0.121, -0.089,  0.102, -0.071, -0.089,  0.052,
        0.213, -0.089, -0.232, -0.07 ,  0.   ])

In [ ]:
a=[1,2,3,4]
b='abcd'

print(list(zip(b,a)))

[('a', 1), ('b', 2), ('c', 3), ('d', 4)]

In [ ]:
dict(zip(dv.get_feature_names_out(), model.coef_[0].round(3)))

{'contract=month-to-month': np.float64(0.476),
 'contract=one_year': np.float64(-0.175),
 'contract=two_year': np.float64(-0.408),
 'dependents=no': np.float64(-0.03),
 'dependents=yes': np.float64(-0.078),
 'deviceprotection=no': np.float64(0.063),
 'deviceprotection=no_internet_service': np.float64(-0.089),
 'deviceprotection=yes': np.float64(-0.081),
 'gender=female': np.float64(-0.034),
 'gender=male': np.float64(-0.073),
 'internetservice=dsl': np.float64(-0.336),
 'internetservice=fiber_optic': np.float64(0.317),
 'internetservice=no': np.float64(-0.089),
 'monthlycharges': np.float64(0.004),
 'multiplelines=no': np.float64(-0.258),
 'multiplelines=no_phone_service': np.float64(0.142),
 'multiplelines=yes': np.float64(0.009),
 'onlinebackup=no': np.float64(0.063),
 'onlinebackup=no_internet_service': np.float64(-0.089),
 'onlinebackup=yes': np.float64(-0.081),
 'onlinesecurity=no': np.float64(0.266),
 'onlinesecurity=no_internet_service': np.float64(-0.089),
 'onlinesecurity=yes': np.float64(-0.284),
 'paperlessbilling=no': np.float64(-0.231),
 'paperlessbilling=yes': np.float64(0.123),
 'partner=no': np.float64(-0.166),
 'partner=yes': np.float64(0.059),
 'paymentmethod=bank_transfer_(automatic)': np.float64(-0.087),
 'paymentmethod=credit_card_(automatic)': np.float64(-0.032),
 'paymentmethod=electronic_check': np.float64(0.07),
 'paymentmethod=mailed_check': np.float64(-0.059),
 'phoneservice=no': np.float64(0.142),
 'phoneservice=yes': np.float64(-0.25),
 'seniorcitizen': np.float64(0.216),
 'streamingmovies=no': np.float64(-0.121),
 'streamingmovies=no_internet_service': np.float64(-0.089),
 'streamingmovies=yes': np.float64(0.102),
 'streamingtv=no': np.float64(-0.071),
 'streamingtv=no_internet_service': np.float64(-0.089),
 'streamingtv=yes': np.float64(0.052),
 'techsupport=no': np.float64(0.213),
 'techsupport=no_internet_service': np.float64(-0.089),
 'techsupport=yes': np.float64(-0.232),
 'tenure': np.float64(-0.07),
 'totalcharges': np.float64(0.0)}

In [ ]:
small = ['contract', 'tenure', 'monthlycharges']

In [ ]:
df_train[small].iloc[:10].to_dict(orient='records')

[{'contract': 'two_year', 'tenure': 72, 'monthlycharges': 115.5},
 {'contract': 'month-to-month', 'tenure': 10, 'monthlycharges': 95.25},
 {'contract': 'month-to-month', 'tenure': 5, 'monthlycharges': 75.55},
 {'contract': 'month-to-month', 'tenure': 5, 'monthlycharges': 80.85},
 {'contract': 'two_year', 'tenure': 18, 'monthlycharges': 20.1},
 {'contract': 'month-to-month', 'tenure': 4, 'monthlycharges': 30.5},
 {'contract': 'month-to-month', 'tenure': 1, 'monthlycharges': 75.1},
 {'contract': 'month-to-month', 'tenure': 1, 'monthlycharges': 70.3},
 {'contract': 'two_year', 'tenure': 72, 'monthlycharges': 19.75},
 {'contract': 'month-to-month', 'tenure': 6, 'monthlycharges': 109.9}]

In [ ]:
dict_train_small = df_train[small].to_dict(orient='records')
dict_val_small = df_val[small].to_dict(orient='records')

In [ ]:
dv_small = DictVectorizer(sparse=False)
dv_small.fit(dict_train_small)

DictVectorizer(sparse=False)

In [ ]:
dv_small.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'monthlycharges', 'tenure'], dtype=object)

In [ ]:
X_train_small = dv_small.transform(dict_train_small)

In [ ]:
model_small = LogisticRegression()
model_small.fit(X_train_small, y_train)

LogisticRegression()

In [ ]:
w0 = model_small.intercept_[0]
w0.round(3)

np.float64(-2.478)

In [ ]:
w = model_small.coef_[0]
w.round(3)

array([ 0.971, -0.024, -0.948,  0.027, -0.036])

In [ ]:
dict(zip(dv_small.get_feature_names_out(), w.round(3))) #the weights

{'contract=month-to-month': np.float64(0.971),
 'contract=one_year': np.float64(-0.024),
 'contract=two_year': np.float64(-0.948),
 'monthlycharges': np.float64(0.027),
 'tenure': np.float64(-0.036)}

Example

Customer A - monthly contract, 60 usd / month, 1 month with us

Customer B - two_year contract, 30 usd / month, 24 months with us

Due to one hot encoding, the variables in contract that are needed turn hot ie become 1

In [ ]:
#Customer A
A = -2.47 + ((1* 0.97) + (0 * (-0.024)) + (0 * (-0.948))) + 60*0.027 + 1 * (-0.036)
A, sigmoid(A)

(0.08399999999999966, np.float64(0.5209876607065322))

Customer A probability of churn is 42% which means the customer is going to churn

In [ ]:
#Customer B
B = -2.48 + ((0 * 0.97) + (0 * (-0.024)) + (1 * (-0.948))) + 30*0.027 + 24 * (-0.036)
B, sigmoid(B)

(-3.4819999999999998, np.float64(0.02982874736022579))

The probabily of churn is 30% (which is below 0.5 or 50%) and therefore this customer is not going to churn

## 3.12 Using the Model

Training the model using the full train dataset

Steps 
- Turn the dataset to dictionaries
- Get the feature matrix
- Train the model on these feature matrix
- Repeat for the test dataset
- Get predictions
- Check accuracy

In [ ]:
dict_full_train = df_full_train[categorical + numerical].to_dict(orient='records')

In [ ]:
dv = DictVectorizer(sparse=False)
X_full_train = dv.fit_transform(dict_full_train)
X_full_train

NameError: name 'DictVectorizer' is not defined

In [ ]:
y_full_train = df_full_train.churn.values

In [ ]:
model = LogisticRegression()
model.fit(X_full_train, y_full_train)

e:\Data Science\gachau_learning\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
dict_test = df_test[categorical + numerical].to_dict(orient='records')
X_test = dv.transform(dict_test)

In [ ]:
y_pred = model.predict_proba(X_test)[:,1]

In [ ]:
churn_decision = y_pred >= 0.5

In [ ]:
(churn_decision == y_test).mean()

np.float64(0.8140525195173882)